apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-etcd-pvc
  namespace: milvus  # 将PVC也放入ai-services命名空间
spec:
  accessModes: #卷可以被单个节点以读写方式挂载，避免并发写入导致数据损坏或状态不一致
    - ReadWriteOnce
  storageClassName: openebs-hostpath-retain
  resources:
    requests:
      storage: 10Gi

---
# --- 为minio创建PV ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-minio-pvc
  namespace: milvus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath-retain
  resources:
    requests:
      storage: 20Gi
---
# --- 为standalone组件创建PV ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-standalone-pvc
  namespace: milvus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath-retain
  resources:
    requests:
      storage: 50Gi

