apiVersion: v1
kind: Namespace
metadata:
  name: milvus
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: milvus-standalone-pv
spec:
  capacity:
    storage: 50Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath: { path: "/data/milvus"}
