apiVersion: v1
kind: Namespace
metadata:
  name: milvus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus
  namespace: milvus
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: "openebs-hostpath"
resources:
  requests:
    storage: 50Gi
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
